# Generated by Django 4.2.7 on 2023-11-27 10:43

from django.db import migrations, models
import django.db.models.deletion
import magnat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=80)),
                ('summary', models.CharField(max_length=400)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=80)),
                ('tel_nomer', models.CharField(max_length=13, validators=[magnat.models.validate_phone_number])),
                ('tex_zadacha', models.FileField(blank=True, null=True, upload_to='user_texzadacha')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Kutishda'), (2, 'Olmadi'), (3, 'Rad etilgan'), (4, "Qo'ng'iroq qilingan"), (5, 'Boshqa')], default=1)),
                ('sabab', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-update_at'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='worker/')),
                ('name', models.CharField(max_length=80)),
                ('familiya', models.CharField(blank=True, max_length=80, null=True)),
                ('sohasi', models.PositiveIntegerField(choices=[(1, 'SMM'), (2, 'Director'), (3, 'Programmer'), (4, 'Project Manager'), (5, 'Graphic Designer')], default=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='portfolio/')),
                ('youtube_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magnat.mediacategory')),
            ],
            options={
                'ordering': ['-created_at', '-update_at'],
            },
        ),
    ]
