# Generated by Django 4.2.7 on 2023-11-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
