# Generated by Django 4.2.7 on 2023-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnat', '0003_rename_user_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sana',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
