# Generated by Django 4.2.7 on 2023-12-04 06:28

from django.db import migrations, models
import magnat.custom_validator


class Migration(migrations.Migration):

    dependencies = [
        ('magnat', '0005_blog_rename_worker_hodim_rename_client_mijoz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-status'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Commentlar'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.FileField(upload_to='blog/', validators=[magnat.custom_validator.validate_image_size]),
        ),
    ]
