# Generated by Django 4.2.7 on 2023-12-04 06:31

from django.db import migrations, models
import magnat.custom_validator


class Migration(migrations.Migration):

    dependencies = [
        ('magnat', '0006_alter_blog_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mijoz',
            name='tex_zadacha',
            field=models.FileField(blank=True, null=True, upload_to='user_texzadacha', validators=[magnat.custom_validator.validate_tex_zadacha]),
        ),
    ]
