# Generated by Django 4.2.7 on 2023-12-04 11:28

from django.db import migrations, models
import magnat.custom_validator


class Migration(migrations.Migration):

    dependencies = [
        ('magnat', '0007_alter_mijoz_tex_zadacha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/', validators=[magnat.custom_validator.validate_portfolio]),
        ),
    ]
